//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 05:01:15 PM IST 
//


package com.gridpoint.energy.domainmodel.masscec.wsclient.ardata;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for monthlyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="monthlyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kwhRegistry" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="regDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="serviceCostsInDollars" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monthlyType", propOrder = {
    "kwhRegistry",
    "regDateTime",
    "serviceCostsInDollars"
})
@XmlSeeAlso({
    PvSpecificMonthlyData.class
})
public class MonthlyType {

    @XmlElement(required = true)
    protected BigDecimal kwhRegistry;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar regDateTime;
    protected BigDecimal serviceCostsInDollars;

    /**
     * Gets the value of the kwhRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKwhRegistry() {
        return kwhRegistry;
    }

    /**
     * Sets the value of the kwhRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKwhRegistry(BigDecimal value) {
        this.kwhRegistry = value;
    }

    /**
     * Gets the value of the regDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegDateTime() {
        return regDateTime;
    }

    /**
     * Sets the value of the regDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegDateTime(XMLGregorianCalendar value) {
        this.regDateTime = value;
    }

    /**
     * Gets the value of the serviceCostsInDollars property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceCostsInDollars() {
        return serviceCostsInDollars;
    }

    /**
     * Sets the value of the serviceCostsInDollars property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceCostsInDollars(BigDecimal value) {
        this.serviceCostsInDollars = value;
    }

}
