//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 05:01:15 PM IST 
//


package com.gridpoint.energy.domainmodel.masscec.wsclient.ardata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.masstech_pts.ar.pts_ar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


	public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PVType }
     * 
     */
    public PVType createPVType() {
        return new PVType();
    }

    /**
     * Create an instance of {@link ARData }
     * 
     */
    public ARData createARData() {
        return new ARData();
    }

    /**
     * Create an instance of {@link MonthlyType }
     * 
     */
    public MonthlyType createMonthlyType() {
        return new MonthlyType();
    }

    /**
     * Create an instance of {@link ARData.PtsSystem.MonthlyData }
     * 
     */
    public ARData.PtsSystem.MonthlyData createARDataPtsSystemMonthlyData() {
        return new ARData.PtsSystem.MonthlyData();
    }

    /**
     * Create an instance of {@link ARData.PtsSystem.IntervalData }
     * 
     */
    public ARData.PtsSystem.IntervalData createARDataPtsSystemIntervalData() {
        return new ARData.PtsSystem.IntervalData();
    }

    /**
     * Create an instance of {@link ARData.PtsSystem }
     * 
     */
    public ARData.PtsSystem createARDataPtsSystem() {
        return new ARData.PtsSystem();
    }


    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }
    

    /**
     * Create an instance of {@link PvSpecificMonthlyData }
     * 
     */
    public PvSpecificMonthlyData createPvSpecificMonthlyData() {
        return new PvSpecificMonthlyData();
    }
}
