//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 05:01:15 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://ar.masstech-pts.org/PTS-AR",
    xmlns = {
          @javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI ="http://ar.masstech-pts.org/PTS-AR")
            }, 
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gridpoint.energy.domainmodel.masscec.wsclient.ardata;
