//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 05:01:15 PM IST 
//


package com.gridpoint.energy.domainmodel.masscec.wsclient.ardata;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PVType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PVType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ar.masstech-pts.org/PTS-AR}entryType">
 *       &lt;sequence>
 *         &lt;element name="avgIrradiance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="avgWindSpeedInMPH" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CurrentInclination" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CurrentAzimuth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PVType", propOrder = {
    "avgIrradiance",
    "avgWindSpeedInMPH",
    "currentInclination",
    "currentAzimuth"
})
public class PVType
    extends EntryType
{

    protected BigDecimal avgIrradiance;
    protected BigDecimal avgWindSpeedInMPH;
    @XmlElement(name = "CurrentInclination")
    protected BigDecimal currentInclination;
    @XmlElement(name = "CurrentAzimuth")
    protected BigDecimal currentAzimuth;

    /**
     * Gets the value of the avgIrradiance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvgIrradiance() {
        return avgIrradiance;
    }

    /**
     * Sets the value of the avgIrradiance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvgIrradiance(BigDecimal value) {
        this.avgIrradiance = value;
    }

    /**
     * Gets the value of the avgWindSpeedInMPH property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvgWindSpeedInMPH() {
        return avgWindSpeedInMPH;
    }

    /**
     * Sets the value of the avgWindSpeedInMPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvgWindSpeedInMPH(BigDecimal value) {
        this.avgWindSpeedInMPH = value;
    }

    /**
     * Gets the value of the currentInclination property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentInclination() {
        return currentInclination;
    }

    /**
     * Sets the value of the currentInclination property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentInclination(BigDecimal value) {
        this.currentInclination = value;
    }

    /**
     * Gets the value of the currentAzimuth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentAzimuth() {
        return currentAzimuth;
    }

    /**
     * Sets the value of the currentAzimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentAzimuth(BigDecimal value) {
        this.currentAzimuth = value;
    }

}
